'use client';

import Link from 'next/link';
import { ArrowRight, ArrowLeft, ScrollText, CheckCircle } from 'lucide-react';

export default function DecisionsDoc() {
  return (
    <div className="max-w-4xl">
      {/* Page Header */}
      <span className="text-xs font-mono uppercase tracking-wider text-purple-400 font-bold mb-2 block">
        Guide — 07
      </span>
      <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-white mb-4">
        On-Chain Decision Logs
      </h1>
      <p className="text-slate-400 text-base sm:text-lg mb-8 leading-relaxed font-light">
        SovereignMind records all agent deliberations and cycle actions on the blockchain. This guide covers how to read decision records and verify execution receipts on-chain.
      </p>

      <h2 className="text-xl sm:text-2xl font-semibold text-slate-100 mt-10 mb-4 border-b border-slate-800/80 pb-2">
        Anatomy of a Decision Record
      </h2>
      <p className="text-slate-300 mb-6 leading-relaxed text-sm sm:text-base">
        When you visit the **Decisions** page, you are looking at a history of all executed agent cycles. Each card represents a single cycle and contains the following data points:
      </p>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
        <div className="bg-slate-900/40 border border-slate-800/80 p-5 rounded-xl">
          <h4 className="font-semibold text-white text-sm mb-1">Decision Title & Action</h4>
          <p className="text-slate-400 text-xs leading-relaxed">
            Identifies the cycle number and the core transaction outcome (e.g. <em>Rebalance</em>, <em>Hold Assets</em>, <em>Adjust Weights</em>).
          </p>
        </div>
        <div className="bg-slate-900/40 border border-slate-800/80 p-5 rounded-xl">
          <h4 className="font-semibold text-white text-sm mb-1">Confidence Score</h4>
          <p className="text-slate-400 text-xs leading-relaxed">
            A metric (0% to 100%) generated by the CEO agent model representing its certainty regarding the recommended reallocation.
          </p>
        </div>
        <div className="bg-slate-900/40 border border-slate-800/80 p-5 rounded-xl col-span-1 sm:col-span-2">
          <h4 className="font-semibold text-white text-sm mb-1">Agent Rationale</h4>
          <p className="text-slate-400 text-xs leading-relaxed">
            The actual English text output generated by the LLM on-chain explaining the market analysis, CFO risk assessments, and why the specific action was chosen.
          </p>
        </div>
      </div>

      <h2 className="text-xl sm:text-2xl font-semibold text-slate-100 mt-10 mb-4 border-b border-slate-800/80 pb-2">
        Somnia Consensus Receipts
      </h2>
      <p className="text-slate-300 mb-4 leading-relaxed text-sm sm:text-base">
        A critical feature of the Somnia L1 is its native verification of off-chain data feeds and LLM runs. Each decision triggers events emitting a unique receipt.
      </p>

      <div className="bg-purple-950/20 border border-purple-500/20 rounded-2xl p-5 mb-8 flex gap-4">
        <CheckCircle className="text-purple-400 shrink-0 mt-1" size={20} />
        <div>
          <h4 className="font-semibold text-purple-200 text-sm mb-1">Verifying Receipts</h4>
          <p className="text-slate-300 text-xs sm:text-sm leading-relaxed mb-3">
            Every decision card in the dashboard features a **Receipt** badge. Clicking it launches the Receipt Modal, displaying:
          </p>
          <ul className="list-disc list-inside space-y-1 text-slate-400 text-xs sm:text-sm pl-1">
            <li>Request ID: The index of the query in the Somnia Agent Runner.</li>
            <li>Validator Signatures: The proof that consensus was reached.</li>
            <li>Model Seed & Temp: Parameters verifying the deterministic execution environment.</li>
          </ul>
        </div>
      </div>

      <p className="text-slate-300 mb-6 leading-relaxed text-sm sm:text-base">
        By copying the transaction hash or request ID and visiting the **Somnia Block Explorer** (Shannon Testnet), developers and users can inspect the raw bytecode events, confirming that the CFO or CEO did indeed execute under the blockchain's consensus bounds without any external manipulation.
      </p>

      {/* Navigation Buttons */}
      <div className="border-t border-slate-800/60 pt-6 flex justify-between">
        <Link
          href="/docs/treasury"
          className="flex items-center gap-2 text-slate-400 hover:text-slate-300 text-sm font-semibold transition-colors"
        >
          <ArrowLeft size={16} /> Previous: Treasury Management
        </Link>
        <Link
          href="/docs/settings"
          className="flex items-center gap-2 text-purple-400 hover:text-purple-300 text-sm font-semibold transition-colors"
        >
          Next: System Configuration <ArrowRight size={16} />
        </Link>
      </div>
    </div>
  );
}
