'use client';

import Link from 'next/link';
import { ArrowRight, ArrowLeft, CheckCircle } from 'lucide-react';

export default function DecisionsDoc() {
  return (
    <div className="max-w-4xl">
      {/* Page Header */}
      <span className="text-[11px] font-label-caps uppercase tracking-wider text-[var(--color-primary)] font-bold mb-2 block">
        Guide — 07
      </span>
      <h1 className="text-3xl sm:text-4xl font-display-lg font-bold tracking-tight text-white mb-4">
        On-Chain Decision Logs
      </h1>
      <p className="text-[var(--color-on-surface)]/80 font-body-md text-base sm:text-lg mb-8 leading-relaxed font-light">
        SovereignMind records all agent deliberations and cycle actions on the blockchain. This guide covers how to read decision records and verify execution receipts on-chain.
      </p>

      <h2 className="text-xl sm:text-2xl font-display-lg font-semibold text-white mt-10 mb-4 border-b border-white/10 pb-2">
        Anatomy of a Decision Record
      </h2>
      <p className="text-[var(--color-on-surface)]/80 font-body-md mb-6 leading-relaxed text-sm sm:text-base">
        When you visit the <strong className="text-white">Decisions</strong> page, you are looking at a history of all executed agent cycles. Each card represents a single cycle and contains the following data points:
      </p>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
        <div className="glass-dark bg-white/5 border border-white/10 p-5 rounded-xl hover:border-[var(--color-primary)]/30 transition-colors duration-300">
          <h4 className="font-display-lg font-semibold text-white text-sm md:text-base mb-1">Decision Title & Action</h4>
          <p className="text-[var(--color-on-surface)]/60 font-body-md text-xs sm:text-sm leading-relaxed">
            Identifies the cycle number and the core transaction outcome (e.g. <em className="text-white">Rebalance</em>, <em className="text-white">Hold Assets</em>, <em className="text-white">Adjust Weights</em>).
          </p>
        </div>
        <div className="glass-dark bg-white/5 border border-white/10 p-5 rounded-xl hover:border-[var(--color-primary)]/30 transition-colors duration-300">
          <h4 className="font-display-lg font-semibold text-white text-sm md:text-base mb-1">Confidence Score</h4>
          <p className="text-[var(--color-on-surface)]/60 font-body-md text-xs sm:text-sm leading-relaxed">
            A metric (0% to 100%) generated by the CEO agent model representing its certainty regarding the recommended reallocation.
          </p>
        </div>
        <div className="glass-dark bg-white/5 border border-white/10 p-5 rounded-xl col-span-1 sm:col-span-2 hover:border-[var(--color-primary)]/30 transition-colors duration-300">
          <h4 className="font-display-lg font-semibold text-white text-sm md:text-base mb-1">Agent Rationale</h4>
          <p className="text-[var(--color-on-surface)]/60 font-body-md text-xs sm:text-sm leading-relaxed">
            The actual English text output generated by the LLM on-chain explaining the market analysis, CFO risk assessments, and why the specific action was chosen.
          </p>
        </div>
      </div>

      <h2 className="text-xl sm:text-2xl font-display-lg font-semibold text-white mt-10 mb-4 border-b border-white/10 pb-2">
        Somnia Consensus Receipts
      </h2>
      <p className="text-[var(--color-on-surface)]/80 font-body-md mb-4 leading-relaxed text-sm sm:text-base">
        A critical feature of the Somnia L1 is its native verification of off-chain data feeds and LLM runs. Each decision triggers events emitting a unique receipt.
      </p>

      <div className="glass-dark bg-[var(--color-primary)]/5 border border-[var(--color-primary)]/20 rounded-2xl p-5 mb-8 flex gap-4 shadow-[0_0_20px_rgba(207,188,255,0.05)]">
        <CheckCircle className="text-[var(--color-primary)] shrink-0 mt-1" size={20} />
        <div>
          <h4 className="font-display-lg font-semibold text-white text-sm md:text-base mb-1">Verifying Receipts</h4>
          <p className="text-[var(--color-on-surface)]/70 font-body-md text-xs sm:text-sm leading-relaxed mb-3">
            Every decision card in the dashboard features a <strong className="text-white">Receipt</strong> badge. Clicking it launches the Receipt Modal, displaying:
          </p>
          <ul className="list-disc list-inside space-y-1 text-[var(--color-on-surface)]/60 font-body-md text-xs sm:text-sm pl-1">
            <li>Request ID: The index of the query in the Somnia Agent Runner.</li>
            <li>Validator Signatures: The proof that consensus was reached.</li>
            <li>Model Seed & Temp: Parameters verifying the deterministic execution environment.</li>
          </ul>
        </div>
      </div>

      <p className="text-[var(--color-on-surface)]/80 font-body-md mb-6 leading-relaxed text-sm sm:text-base">
        By copying the transaction hash or request ID and visiting the <strong className="text-white">Somnia Block Explorer</strong> (Shannon Testnet), developers and users can inspect the raw bytecode events, confirming that the CFO or CEO did indeed execute under the blockchain&apos;s consensus bounds without any external manipulation.
      </p>

      {/* Navigation Buttons */}
      <div className="border-t border-white/10 pt-6 flex justify-between">
        <Link
          href="/docs/treasury"
          className="flex items-center gap-2 text-[var(--color-on-surface)]/60 hover:text-white font-label-caps text-xs sm:text-sm font-bold tracking-wider uppercase transition-colors"
        >
          <ArrowLeft size={16} /> Previous: Treasury Management
        </Link>
        <Link
          href="/docs/settings"
          className="flex items-center gap-2 text-[var(--color-primary)] hover:text-white font-label-caps text-xs sm:text-sm font-bold tracking-wider uppercase transition-colors"
        >
          Next: System Configuration <ArrowRight size={16} />
        </Link>
      </div>
    </div>
  );
}
