'use client';

// ============================================================
// SovereignMind — Smart Contract Configuration
// ============================================================
// Central contract config that exports all addresses + ABIs.
// Addresses are loaded from deployed-addresses.json (generated by deploy script).
// ABIs are loaded from the abis/ directory (generated by copy-abis script).

import AgentRegistryABI from './abis/AgentRegistry.json';
import TreasuryVaultABI from './abis/TreasuryVault.json';
import CEOAgentABI from './abis/CEOAgent.json';
import CFOAgentABI from './abis/CFOAgent.json';
import CMOAgentABI from './abis/CMOAgent.json';
import PriceOracleABI from './abis/PriceOracle.json';
import SyntheticSwapRouterABI from './abis/SyntheticSwapRouter.json';
import VaultSharesABI from './abis/VaultShares.json';
import deployedAddresses from './deployed-addresses.json';

export type ContractName = 'agentRegistry' | 'treasuryVault' | 'ceoAgent' | 'cfoAgent' | 'cmoAgent' | 'priceOracle' | 'syntheticSwapRouter' | 'vaultShares';

const addr = deployedAddresses.contracts;

export const contracts = {
  agentRegistry: {
    address: addr.agentRegistry as `0x${string}`,
    abi: AgentRegistryABI,
  },
  treasuryVault: {
    address: addr.treasuryVault as `0x${string}`,
    abi: TreasuryVaultABI,
  },
  ceoAgent: {
    address: addr.ceoAgent as `0x${string}`,
    abi: CEOAgentABI,
  },
  cfoAgent: {
    address: addr.cfoAgent as `0x${string}`,
    abi: CFOAgentABI,
  },
  cmoAgent: {
    address: addr.cmoAgent as `0x${string}`,
    abi: CMOAgentABI,
  },
  priceOracle: {
    address: (addr.priceOracle || '') as `0x${string}`,
    abi: PriceOracleABI,
  },
  syntheticSwapRouter: {
    address: (addr.syntheticSwapRouter || '') as `0x${string}`,
    abi: SyntheticSwapRouterABI,
  },
  vaultShares: {
    address: (addr.vaultShares || '') as `0x${string}`,
    abi: VaultSharesABI,
  },
} as const;

export const agentRunnerAddress = deployedAddresses.config.agentRunnerAddress as `0x${string}`;
export const chainId = deployedAddresses.chainId;
