'use client';

// ============================================================
// SovereignMind — Smart Contract Configuration
// ============================================================
// Central contract config that exports all addresses + ABIs.
// Addresses are loaded from deployed-addresses.json (generated by deploy script).
// ABIs are loaded from the abis/ directory (generated by copy-abis script).

import AgentRegistryABI from './abis/AgentRegistry.json';
import TreasuryVaultABI from './abis/TreasuryVault.json';
import CEOAgentABI from './abis/CEOAgent.json';
import CFOAgentABI from './abis/CFOAgent.json';
import CMOAgentABI from './abis/CMOAgent.json';
import deployedAddresses from './deployed-addresses.json';

export type ContractName = 'agentRegistry' | 'treasuryVault' | 'ceoAgent' | 'cfoAgent' | 'cmoAgent';

export const contracts = {
  agentRegistry: {
    address: deployedAddresses.contracts.agentRegistry as `0x${string}`,
    abi: AgentRegistryABI,
  },
  treasuryVault: {
    address: deployedAddresses.contracts.treasuryVault as `0x${string}`,
    abi: TreasuryVaultABI,
  },
  ceoAgent: {
    address: deployedAddresses.contracts.ceoAgent as `0x${string}`,
    abi: CEOAgentABI,
  },
  cfoAgent: {
    address: deployedAddresses.contracts.cfoAgent as `0x${string}`,
    abi: CFOAgentABI,
  },
  cmoAgent: {
    address: deployedAddresses.contracts.cmoAgent as `0x${string}`,
    abi: CMOAgentABI,
  },
} as const;

export const agentRunnerAddress = deployedAddresses.config.agentRunnerAddress as `0x${string}`;
export const chainId = deployedAddresses.chainId;
